import PRGExtension.Expression.Defs
import PRGExtension.Expression.SymbolicIndistinguishability
import PRGExtension.Expression.Lemmas.HideEncrypted
import PRGExtension.Expression.ComputationalSemantics.Def
import PRGExtension.ComputationalIndistinguishability.Def

import PRGExtension.Expression.ComputationalSemantics.Games
import PRGExtension.Expression.ComputationalSemantics.Games
import PRGExtension.ComputationalIndistinguishability.Lemmas
import PRGExtension.Expression.ComputationalSemantics.SoundnessProof.HidingOneKey
import PRGExtension.Expression.ComputationalSemantics.SoundnessProof.AdversaryView
import PRGExtension.Expression.ComputationalSemantics.SoundnessProof.FixpointStep
import PRGExtension.Expression.ComputationalSemantics.Efficiency.PolyTime

import PRGExtension.Core.Fixpoints
import Mathlib.Probability.Distributions.Uniform

import Mathlib.Data.Finset.SDiff

/-!
# LM18 Theorem 3: symbolic soundness

(Numbering follows Li--Micciancio, CSF 2018, ePrint 2018/141.  Earlier revisions of this
development cited this result as "Theorem 1"; Theorem 1 there is the independent-keys
characterisation, which is used separately in `SoundnessProof/HidingOnePrgSeed.lean`.)

The bridge between the two halves of the development: if two expressions are *symbolically*
indistinguishable, then their computational semantics are computationally indistinguishable.

`symbolicToSemanticSoundness` is the theorem.  Its proof walks the symbolic relation's
generators — renaming, the PRG-idealisation hops (`PrgRenameRel`), and the fixpoint step that
hides everything the adversary cannot recover — discharging each by a reduction proved in
`SoundnessProof/`.

`symbolicToSemanticSoundnessFromEfficiency` is the same theorem with the PRG reduction's
efficiency derived rather than assumed.  For the version in which *every* efficiency claim
about the reductions is discharged, see `Garbling/Security/SecurityFromPrimitives.lean`.
-/

-- This file proves the soundness theorem: if two expressions are symbolically indistinguishable, then their computational semantics (distributions over bitstrings)  are computationally indistinguishable. The technical details of this proof are in `SoundnessProof/`.

open PRG

/--
  **LM18 Lemma 2 / [Mic09, Corollary 1]**, constructive presentation.

  A *pseudorandom key renaming* is a `𝖦`-preserving map `α_K : S → 𝐊*`.  By
  [Mic09, Lemma 2] every such map is the unique extension of a bijection between
  `Roots(S)` and `Roots(α_K S)`, so the class is generated by

  * bijections of the atomic key variables (`atomic`), and
  * re-rooting one PRG node — identifying `G0 (VarK t)` and `G1 (VarK t)` with two fresh
    independent atomic keys (`idealize`) — together with its inverse (`symm`).

  We take those generators as the definition, and that loses nothing: **[Mic09, Lemma 2] is
  formalised in both directions** in `Expression/Lemmas/PseudorandomRenaming.lean`.  The
  factorisation — that every abstractly `𝖦`-preserving map arises this way — is
  `gPreserving_eq_substKeys`, `gPreserving_ext` and `rootsOf_keySubterms`; the generation
  direction is `prgRenameRel_substKeys_general`, in full, with no freshness hypothesis.  The
  computational content of Lemma 2 is `prgRename` below.

  Example: `α_K : {K₁} → {G0 (K₂)}` maps an atomic key to a non-atomic one.  It is realised
  as `atomic` (renaming the dummy back to `K₁`) composed with `symm (idealize …)`.
-/
inductive PrgRenameRel {s : Shape} : Expression s → Expression s → Prop
  | atomic (r : varRenaming) (hr : validVarRenaming r) (e : Expression s) :
      PrgRenameRel e (applyVarRenaming r e)
  | idealize (e : Expression s) (t idx0 idx1 : ℕ)
      (H_seed : Expression.VarK t ∉ exprKeys e)
      (H_diff : idx0 ≠ idx1)
      (H_fresh0 : Expression.VarK idx0 ∉ keySubterms e)
      (H_fresh1 : Expression.VarK idx1 ∉ keySubterms e) :
      PrgRenameRel e (replacePRG (Expression.VarK t) idx0 idx1 e)
  | symm {e1 e2 : Expression s} : PrgRenameRel e1 e2 → PrgRenameRel e2 e1
  | trans {e1 e2 e3 : Expression s} : PrgRenameRel e1 e2 → PrgRenameRel e2 e3 → PrgRenameRel e1 e3

/--
  **LM18 Lemma 2.**  Expressions related by a pseudorandom key renaming have
  computationally indistinguishable semantics.

  The atomic generator contributes an *exact equality* of distributions
  (`applyRenamePreservesCompSem2`); only the `idealize` generator consumes PRG security.
-/
theorem prgRename
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (enc : encryptionScheme) (prg : prgScheme)
  (HreductionPrg : PrgReductionPolyTime IsPolyTime enc prg)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} {e1 e2 : Expression shape} (H : PrgRenameRel e1 e2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg e1))
    (famDistrLift (exprToFamDistr enc prg e2)) := by
  induction H with
  | atomic r hr e =>
      rw [← applyRenamePreservesCompSem2 enc prg e r hr]
      apply indRfl
  | idealize e t idx0 idx1 H_seed H_diff H0 H1 =>
      exact symbolicToSemanticIndistinguishabilityPrgIdealization IsPolyTime HPolyTime
        enc prg HreductionPrg HPrgSecure e t idx0 idx1 H_seed H_diff H0 H1
  | symm _ ih => exact indSym ih
  | trans _ _ ih1 ih2 => exact indTrans _ ih1 ih2

theorem symbolicToSemanticIndistinguishability
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (enc : encryptionScheme) (prg : prgScheme)
  (Hreduction : EncReductionPolyTime IsPolyTime enc prg)
  (HreductionPrg : PrgReductionPolyTime IsPolyTime enc prg)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  -- Side condition, see `hidingSideCondition` (LM18 Lemma 4 (atomicity)).  Discharging it
  -- in general requires LM18 Lemma 2 / Theorem 1 (pseudorandom key renaming), which is
  -- not yet formalised; it holds whenever `Roots(Keys(·)) ⊆ 𝐊` at every stage of the
  -- fixpoint.  It is vacuously satisfiable for PRG-free expressions.
  (Hatomic1 : ∀ S : Finset (Expression Shape.KeyS), hidingSideCondition (hideEncrypted S expr1))
  (Hatomic2 : ∀ S : Finset (Expression Shape.KeyS), hidingSideCondition (hideEncrypted S expr2))
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) := by
  -- Unfold the pure symbolic structural equivalence
  simp [symIndistinguishable] at Hi
  let ⟨r, Hr, Hi⟩ := Hi
  -- Push the equality down to the distribution semantics
  let fab {X Y : Type} {a b : X} (f : X -> Y) (H : a = b) : f a = f b := by rw [H]
  have Hi2 := fab (exprToFamDistr enc prg) Hi
  -- Normalize and apply renaming
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-applyRenamePreservesCompSem2 enc prg] at Hi2 <;> try assumption
  -- Computational Transitivity Hop 1: expr1 ≈ adversaryView expr1
  apply indTrans (fun {I Spec Output} ↦ IsPolyTime)
  -- HOP 1: Prove expr1 ≈ adversaryView expr1
  exact symbolicToSemanticIndistinguishabilityAdversaryView IsPolyTime HPolyTime enc prg Hreduction HreductionPrg HEncIndCpa HPrgSecure expr1 Hatomic1
  -- HOP 2: adversaryView expr1 ≈ expr2
  rw [Hi2]
  apply indSym
  exact symbolicToSemanticIndistinguishabilityAdversaryView IsPolyTime HPolyTime enc prg Hreduction HreductionPrg HEncIndCpa HPrgSecure expr2 Hatomic2

/--
  Soundness on the PRG-free fragment, with **no** side conditions: if every key subterm of
  both expressions is an atomic variable then `hidingSideCondition` is automatic.

  This is the statement that specialises the extended framework back to the original
  encryption-only one, and it is what a caller with no `G` nodes should use.
-/
theorem symbolicToSemanticIndistinguishabilityAtomic
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (enc : encryptionScheme) (prg : prgScheme)
  (Hreduction : EncReductionPolyTime IsPolyTime enc prg)
  (HreductionPrg : PrgReductionPolyTime IsPolyTime enc prg)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  (HA1 : AtomicKeys expr1) (HA2 : AtomicKeys expr2)
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) :=
  symbolicToSemanticIndistinguishability IsPolyTime HPolyTime enc prg Hreduction HreductionPrg
    HEncIndCpa HPrgSecure expr1 expr2
    (fun S => hidingSideCondition_of_atomicKeys (atomicKeys_hideEncrypted S HA1))
    (fun S => hidingSideCondition_of_atomicKeys (atomicKeys_hideEncrypted S HA2))
    Hi

-- REMOVED (2026-09-16d): `AtomicisationBridge` and
-- `symbolicToSemanticIndistinguishabilityOfBridge`.
--
-- The bridge demanded `∀ S, hidingSideCondition (hideEncrypted S e')` — the side condition
-- at *every* stage of the fixpoint, for a single globally-renamed `e'`.  That is not
-- satisfiable once the expression has any PRG structure: some `S` hides the atomic root of
-- a key chain away, leaving a non-atomic root behind, exactly as
-- `scratch/probes/GarbleSideCondition.lean` exhibits.  A hypothesis nothing can satisfy makes the
-- theorem vacuous, which is the same defect as the `prgSchemeSecure` bug fixed earlier.
--
-- The atomicisation has to happen *per fixpoint step*, not once globally.  The obligation
-- is therefore stated as `FixpointStepSound` (see `AdversaryView.lean`), and
-- `symbolicToSemanticIndistinguishabilityOfStep` below is the corresponding theorem.

/--
  **Soundness with no side conditions, given one sound fixpoint step.**

  `FixpointStepSound` is now the single outstanding obligation of the whole expression
  layer.  Everything else — IND-CPA hiding, PRG idealisation, renaming, normalisation, the
  fixpoint plumbing — is proved.
-/
theorem symbolicToSemanticIndistinguishabilityOfStep
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (enc : encryptionScheme)
  (prg : prgScheme)
  (Hstep : FixpointStepSound (fun {_ _ _} => IsPolyTime) enc prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) := by
  simp [symIndistinguishable] at Hi
  let ⟨r, Hr, Hi⟩ := Hi
  let fab {X Y : Type} {a b : X} (f : X -> Y) (H : a = b) : f a = f b := by rw [H]
  have Hi2 := fab (exprToFamDistr enc prg) Hi
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-applyRenamePreservesCompSem2 enc prg] at Hi2 <;> try assumption
  apply indTrans (fun {I Spec Output} ↦ IsPolyTime)
  · exact symbolicToSemanticIndistinguishabilityAdversaryViewOfStep IsPolyTime enc prg Hstep expr1
  · rw [Hi2]
    exact indSym (symbolicToSemanticIndistinguishabilityAdversaryViewOfStep IsPolyTime enc prg Hstep expr2)

/--
  **Soundness of the symbolic model, with no side conditions.**

  Symbolically indistinguishable expressions have computationally indistinguishable
  semantics, given only IND-CPA security of the encryption scheme and security of the PRG.
  This is LM18 Theorem 3 for the PRG-extended algebra: `fixpointStepSound` discharges the
  last obligation, so the theorem now carries no `hidingSideCondition` and no atomicity
  hypothesis.
-/
theorem symbolicToSemanticSoundness
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (enc : encryptionScheme) (prg : prgScheme)
  (Hreduction : EncReductionPolyTime IsPolyTime enc prg)
  (HreductionPrg : PrgReductionPolyTime IsPolyTime enc prg)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) :=
  symbolicToSemanticIndistinguishabilityOfStep IsPolyTime HPolyTime enc prg
    (fixpointStepSound IsPolyTime HPolyTime enc prg Hreduction HreductionPrg
      HEncIndCpa HPrgSecure)
    expr1 expr2 Hi

/--
  **Soundness with the PRG reduction's efficiency *derived* rather than assumed.**

  Same conclusion as `symbolicToSemanticSoundness`, but instead of taking
  `PrgReductionPolyTime` on faith it takes the two claims that imply it: that the reduction's
  fixed-size sampling prefix is efficient, and that the scheme's own evaluation is
  (LM18 Definition 1).  See `ComputationalSemantics/PolyTime.lean`.

  `EncReductionPolyTime` is still a hypothesis — that one needs a cost semantics for
  `OracleComp`, since `reductionToOracle` recurses over the expression while querying.
-/
theorem symbolicToSemanticSoundnessFromEfficiency
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (enc : encryptionScheme) (prg : prgScheme)
  (Hreduction : EncReductionPolyTime IsPolyTime enc prg)
  (Hsampler : ∀ {s : Shape} (expr : Expression s) (targetSeed : Expression Shape.KeyS)
    (idx0 idx1 : ℕ), IsPolyTime (prgEnvSampler expr targetSeed idx0 idx1))
  (Heval : EfficientEvalPrg IsPolyTime enc prg)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) :=
  symbolicToSemanticSoundness IsPolyTime HPolyTime enc prg Hreduction
    (reductionToPrgOracle_polyTime IsPolyTime HPolyTime enc prg Hsampler Heval)
    HEncIndCpa HPrgSecure expr1 expr2 Hi
