import PRGExtension.Expression.Defs
import PRGExtension.Expression.SymbolicIndistinguishability
import PRGExtension.Expression.Lemmas.HideEncrypted
import PRGExtension.Expression.ComputationalSemantics.Def
import PRGExtension.ComputationalIndistinguishability.Def

import PRGExtension.Expression.ComputationalSemantics.EncryptionIndCpa
import PRGExtension.Expression.ComputationalSemantics.PrgSecurity
import PRGExtension.ComputationalIndistinguishability.Lemmas
import PRGExtension.Expression.ComputationalSemantics.SoundnessProof.HidingOneKey
import PRGExtension.Expression.ComputationalSemantics.SoundnessProof.AdversaryView

import PRGExtension.Core.Fixpoints
import Mathlib.Probability.Distributions.Uniform

import Mathlib.Data.Finset.SDiff

-- This file proves the soundness theorem: if two expressions are symbolically indistinguishable, then their computational semantics (distributions over bitstrings)  are computationally indistinguishable. The technical details of this proof are in `SoundnessProof/`.

open PRG

/--
  **LM18 Lemma 2 / [Mic09, Corollary 1]**, constructive presentation.

  A *pseudorandom key renaming* is a `𝖦`-preserving map `α_K : S → 𝐊*`.  By
  [Mic09, Lemma 2] every such map is the unique extension of a bijection between
  `Roots(S)` and `Roots(α_K S)`, so the class is generated by

  * bijections of the atomic key variables (`atomic`), and
  * re-rooting one PRG node — identifying `G0 (VarK t)` and `G1 (VarK t)` with two fresh
    independent atomic keys (`idealize`) — together with its inverse (`symm`).

  We take those generators as the definition.  What is *not* formalised here is the purely
  symbolic factorisation result [Mic09, Lemma 2] itself, i.e. that every abstractly
  `𝖦`-preserving map arises this way; the computational content of Lemma 2 is `prgRename`
  below.

  Example: `α_K : {K₁} → {G0 (K₂)}` maps an atomic key to a non-atomic one.  It is realised
  as `atomic` (renaming the dummy back to `K₁`) composed with `symm (idealize …)`.
-/
inductive PrgRenameRel {s : Shape} : Expression s → Expression s → Prop
  | atomic (r : varRenaming) (hr : validVarRenaming r) (e : Expression s) :
      PrgRenameRel e (applyVarRenaming r e)
  | idealize (e : Expression s) (t idx0 idx1 : ℕ)
      (H_seed : Expression.VarK t ∉ exprKeys e)
      (H_diff : idx0 ≠ idx1)
      (H_fresh0 : Expression.VarK idx0 ∉ keySubterms e)
      (H_fresh1 : Expression.VarK idx1 ∉ keySubterms e) :
      PrgRenameRel e (replacePRG (Expression.VarK t) idx0 idx1 e)
  | symm {e1 e2 : Expression s} : PrgRenameRel e1 e2 → PrgRenameRel e2 e1
  | trans {e1 e2 e3 : Expression s} : PrgRenameRel e1 e2 → PrgRenameRel e2 e3 → PrgRenameRel e1 e3

/--
  **LM18 Lemma 2.**  Expressions related by a pseudorandom key renaming have
  computationally indistinguishable semantics.

  The atomic generator contributes an *exact equality* of distributions
  (`applyRenamePreservesCompSem2`); only the `idealize` generator consumes PRG security.
-/
theorem prgRename
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (HreductionPrg : forall (enc_ : encryptionScheme) (prg_ : prgScheme) (s_ : Shape) (expr_ : Expression s_) (targetSeed_ : Expression Shape.KeyS) (idx0_ idx1_ : ℕ),
    IsPolyTime (fun κ => reductionToPrgOracle enc_ prg_ expr_ targetSeed_ idx0_ idx1_ κ))
  (enc : encryptionScheme) (prg : prgScheme)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} {e1 e2 : Expression shape} (H : PrgRenameRel e1 e2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg e1))
    (famDistrLift (exprToFamDistr enc prg e2)) := by
  induction H with
  | atomic r hr e =>
      rw [← applyRenamePreservesCompSem2 enc prg e r hr]
      apply indRfl
  | idealize e t idx0 idx1 H_seed H_diff H0 H1 =>
      exact symbolicToSemanticIndistinguishabilityPrgIdealization IsPolyTime HPolyTime
        HreductionPrg enc prg HPrgSecure e t idx0 idx1 H_seed H_diff H0 H1
  | symm _ ih => exact indSym ih
  | trans _ _ ih1 ih2 => exact indTrans _ ih1 ih2

theorem symbolicToSemanticIndistinguishability
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (Hreduction : ∀ (enc : encryptionScheme) (prg : prgScheme) (shape : Shape) (expr : Expression shape) (key₀ : ℕ),
    IsPolyTime (reductionHidingOneKey enc prg expr key₀))
  (HreductionPrg : forall (enc_ : encryptionScheme) (prg_ : prgScheme) (s_ : Shape) (expr_ : Expression s_) (targetSeed_ : Expression Shape.KeyS) (idx0_ idx1_ : ℕ),
    IsPolyTime (fun κ => reductionToPrgOracle enc_ prg_ expr_ targetSeed_ idx0_ idx1_ κ))
  (enc : encryptionScheme)
  (prg : prgScheme)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  -- Side condition, see `hidingSideCondition` (LM18 Lemma 3, property 1).  Discharging it
  -- in general requires LM18 Lemma 2 / Theorem 1 (pseudorandom key renaming), which is
  -- not yet formalised; it holds whenever `Roots(Keys(·)) ⊆ 𝐊` at every stage of the
  -- fixpoint.  It is vacuously satisfiable for PRG-free expressions.
  (Hatomic1 : ∀ S : Finset (Expression Shape.KeyS), hidingSideCondition (hideEncrypted S expr1))
  (Hatomic2 : ∀ S : Finset (Expression Shape.KeyS), hidingSideCondition (hideEncrypted S expr2))
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) := by
  -- Unfold the pure symbolic structural equivalence
  simp [symIndistinguishable] at Hi
  let ⟨r, Hr, Hi⟩ := Hi
  -- Push the equality down to the distribution semantics
  let fab {X Y : Type} {a b : X} (f : X -> Y) (H : a = b) : f a = f b := by rw [H]
  have Hi2 := fab (exprToFamDistr enc prg) Hi
  -- Normalize and apply renaming
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-applyRenamePreservesCompSem2 enc prg] at Hi2 <;> try assumption
  -- Computational Transitivity Hop 1: expr1 ≈ adversaryView expr1
  apply indTrans (fun {I Spec Output} ↦ IsPolyTime)
  -- HOP 1: Prove expr1 ≈ adversaryView expr1
  exact symbolicToSemanticIndistinguishabilityAdversaryView IsPolyTime HPolyTime Hreduction HreductionPrg enc prg HEncIndCpa HPrgSecure expr1 Hatomic1
  -- HOP 2: adversaryView expr1 ≈ expr2
  rw [Hi2]
  apply indSym
  exact symbolicToSemanticIndistinguishabilityAdversaryView IsPolyTime HPolyTime Hreduction HreductionPrg enc prg HEncIndCpa HPrgSecure expr2 Hatomic2

/--
  Soundness on the PRG-free fragment, with **no** side conditions: if every key subterm of
  both expressions is an atomic variable then `hidingSideCondition` is automatic.

  This is the statement that specialises the extended framework back to the original
  encryption-only one, and it is what a caller with no `G` nodes should use.
-/
theorem symbolicToSemanticIndistinguishabilityAtomic
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (Hreduction : ∀ (enc : encryptionScheme) (prg : prgScheme) (shape : Shape) (expr : Expression shape) (key₀ : ℕ),
    IsPolyTime (reductionHidingOneKey enc prg expr key₀))
  (HreductionPrg : forall (enc_ : encryptionScheme) (prg_ : prgScheme) (s_ : Shape) (expr_ : Expression s_) (targetSeed_ : Expression Shape.KeyS) (idx0_ idx1_ : ℕ),
    IsPolyTime (fun κ => reductionToPrgOracle enc_ prg_ expr_ targetSeed_ idx0_ idx1_ κ))
  (enc : encryptionScheme)
  (prg : prgScheme)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  {shape : Shape} (expr1 expr2 : Expression shape)
  (HA1 : AtomicKeys expr1) (HA2 : AtomicKeys expr2)
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) :=
  symbolicToSemanticIndistinguishability IsPolyTime HPolyTime Hreduction HreductionPrg enc prg
    HEncIndCpa HPrgSecure expr1 expr2
    (fun S => hidingSideCondition_of_atomicKeys (atomicKeys_hideEncrypted S HA1))
    (fun S => hidingSideCondition_of_atomicKeys (atomicKeys_hideEncrypted S HA2))
    Hi

/--
  **The one remaining gap between the framework and the garbling application.**

  `hidingSideCondition` (LM18 Lemma 3, property 1: "the keys being hidden are atomic") is
  **false** for PRG garbled circuits.  `scratch/GarbleSideCondition.lean` computes
  `Garble andC (true,true)` — a `NAnd` feeding a `Dup` feeding a second `NAnd` — and finds
  that at the fixpoint the hidden key set is `{G0 K₄, G1 K₄}`, which is not atomic.  That
  is not an artefact of the encoding: it is exactly LM18's observation that
  `Roots(Keys(e)) ⊆ 𝐊` fails once `Dup` derives wire keys with the PRG.

  LM18 closes it with the general case of Lemma 3: rename the roots of `Keys(e)` to fresh
  atomic keys, run the atomic argument, and rename back.  Both renamings are instances of
  `PrgRenameRel`, so the *computational* content is already available (`prgRename`).  What
  is missing is purely symbolic: the construction of that renaming, and the fact that it
  carries the adversary view along.  `AtomicisationBridge` is exactly that statement.

  Given it, `symbolicToSemanticIndistinguishabilityOfBridge` below needs no side
  conditions at all.
-/
def AtomicisationBridge : Prop :=
  ∀ {s : Shape} (e : Expression s),
    ∃ e' : Expression s,
      PrgRenameRel e e' ∧
      (∀ S : Finset (Expression Shape.KeyS), hidingSideCondition (hideEncrypted S e')) ∧
      PrgRenameRel (adversaryView e') (adversaryView e)

/--
  Soundness with **no side conditions**, modulo the single symbolic obligation
  `AtomicisationBridge`.

  Every cryptographic step is discharged: the `PrgRenameRel` hops by `prgRename`
  (PRG security), the adversary-view hop by
  `symbolicToSemanticIndistinguishabilityAdversaryView` (IND-CPA), and the final step by
  the exact-equality normalisation and renaming lemmas.
-/
theorem symbolicToSemanticIndistinguishabilityOfBridge
  (IsPolyTime : PolyFamOracleCompPred)
  (HPolyTime : PolyTimeClosedUnderComposition (fun {_ _ _} => IsPolyTime))
  (Hreduction : ∀ (enc : encryptionScheme) (prg : prgScheme) (shape : Shape) (expr : Expression shape) (key₀ : ℕ),
    IsPolyTime (reductionHidingOneKey enc prg expr key₀))
  (HreductionPrg : forall (enc_ : encryptionScheme) (prg_ : prgScheme) (s_ : Shape) (expr_ : Expression s_) (targetSeed_ : Expression Shape.KeyS) (idx0_ idx1_ : ℕ),
    IsPolyTime (fun κ => reductionToPrgOracle enc_ prg_ expr_ targetSeed_ idx0_ idx1_ κ))
  (enc : encryptionScheme)
  (prg : prgScheme)
  (HEncIndCpa : encryptionSchemeIndCpa (fun {_ _ _} => IsPolyTime) enc)
  (HPrgSecure : prgSchemeSecure (fun {_ _ _} => IsPolyTime) prg)
  (Hbridge : AtomicisationBridge)
  {shape : Shape} (expr1 expr2 : Expression shape)
  (Hi : symIndistinguishable expr1 expr2) :
  CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
    (famDistrLift (exprToFamDistr enc prg expr1))
    (famDistrLift (exprToFamDistr enc prg expr2)) := by
  -- `e ≈ adversaryView e`, via the atomicised representative `e'`
  have hop : ∀ (e : Expression shape),
      CompIndistinguishabilityDistr (fun {_ _ _} => IsPolyTime)
        (famDistrLift (exprToFamDistr enc prg e))
        (famDistrLift (exprToFamDistr enc prg (adversaryView e))) := by
    intro e
    obtain ⟨e', Hren, Hsc, Hview⟩ := Hbridge e
    apply indTrans
    · exact prgRename IsPolyTime HPolyTime HreductionPrg enc prg HPrgSecure Hren
    apply indTrans
    · exact symbolicToSemanticIndistinguishabilityAdversaryView IsPolyTime HPolyTime
        Hreduction HreductionPrg enc prg HEncIndCpa HPrgSecure e' Hsc
    · exact prgRename IsPolyTime HPolyTime HreductionPrg enc prg HPrgSecure Hview
  -- the symbolic equality, pushed to distributions exactly as in the main theorem
  simp [symIndistinguishable] at Hi
  let ⟨r, Hr, Hi⟩ := Hi
  let fab {X Y : Type} {a b : X} (f : X -> Y) (H : a = b) : f a = f b := by rw [H]
  have Hi2 := fab (exprToFamDistr enc prg) Hi
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-normalizeExprToDistr] at Hi2
  rw [<-applyRenamePreservesCompSem2 enc prg] at Hi2 <;> try assumption
  apply indTrans (fun {I Spec Output} ↦ IsPolyTime)
  · exact hop expr1
  · rw [Hi2]
    exact indSym (hop expr2)
