import PRGExtension.Expression.ComputationalSemantics.Efficiency.CostModel

/-!
# A concrete `IsPolyTime`: the class generated by the primitives

`CHECKPOINT.md` §3.1 records why Design B's original step 1 — define
`cost : OracleComp spec α → ℕ` by recursion over the free monad — cannot work: the free monad
records oracle queries and nothing else, so local running time is not a property of an
`OracleComp` term at all (`scratch/findings/CostAttempt.lean` proves it two ways).

The way out is to stop trying to *measure* terms and instead *generate* the class.
`IsPolyTime` becomes the smallest class containing the primitives and closed under the
combinators — an inductive family whose **derivations are the implementations**.  This is
realizability with derivation trees as programs, and it needs no machine model.

What it buys: `PolyTimeModel` and `BitOpsEfficient` stop being assumptions and become
*theorems* (`genPolyTimeModel`, `genBitOpsEfficient`), each clause discharged by the matching
constructor; LM18 Definition 1 becomes a *generator* rather than a hypothesis
(`genEfficientEncVal`, `genEfficientPrgVal`); and the class has no iteration constructor, so
the brute-force distinguisher that makes every query-counting model vacuous is simply not in
it.

## What is in the class

Thirty-three generators, in four groups: the structural ones (`id`, projections, `pair`,
`precomp`, `bind`), the reductions' bit operations (`append`, `keyVar`, `bitExpr`, …), the
cryptographic primitives (`encrypt`, `prg0`, `prg1`), and — added 2026-09-21d to close
finding F8 — general bit-level computation and bounded iteration:

* random access: `index` and `update`, both taking the position **as input**, with
  `bitsToFin` to compute a position from a register;
* logic: `notB`, `andB`, `select` (branch at any poly-sized type), `eqBits`, `xorBits`;
* counting: `finSucc`; non-uniform advice: `constBits`, `constFin`, `constBool`;
* loops: `iterate` (declared polynomial bound) and `iterateIdx` (the same, with the step able
  to see the loop counter — needed for inner loops over bit positions).

**Soundness is by construction.**  Every generator is polynomially bounded, composition and
`bind` preserve that, and iteration runs a declared polynomial number of times over a state
whose type — being a fixed `PolySized` family — cannot widen.  So no member does
superpolynomial work.  In particular **brute-force key search is not in the class**, which is
what makes security against it plausible rather than absurd.

## Completeness for PTIME: what can and cannot be claimed

**A formal completeness theorem is not available here, and the obstruction is structural, not
a matter of effort.**  "The class contains every poly-time function" presupposes a formalised
definition of *poly-time function* — a machine model in Lean — and building one is precisely
the cost that made the circuit-realizability route unattractive and that generating the class
was meant to avoid.  Soundness-by-construction and completeness pull in opposite directions:
soundness is free *because* there is no external reference, and completeness needs one.
Atkey [POPL 2024] obtains completeness because he has that reference (a Dal Lago–Hofmann
realisability model against a standard definition); importing the result would mean importing
the setting.

What Atkey and Hofmann's LFPL *do* contribute is a negative observation worth recording.
Their completeness constructions — the Aehlig–Schwichtenberg nested iterators over a binomial
basis — exist to *manufacture* `p(n)` iterations in a system where one may only iterate over
data already held, and must pay to build more.  With a **declared** bound that machinery is
unnecessary: `iterate` gives `p.eval κ` passes in one constructor.  The hard half of their
completeness proof therefore does not arise, and the remaining half — simulating one machine
step — is what the bit-level generators above are for.

**The informal argument, stated so it can be checked or refuted.**  Take
`S κ = BitVector (w κ) × Fin (w κ) × BitVector (r κ)` — memory, head, registers — which is
`PolySized`.  One step of a random-access machine is then a *constant* number of generators,
independent of `κ`: read at a computed address (`bitsToFin` then `index`), branch
(`eqBits`, `notB`, `andB`, `select`), write at a computed address (`update`), advance
(`finSucc`).  `poly(κ)` such steps is one `iterate`; inner loops over bit positions — a
ripple-carry increment, a memory scan — are `iterateIdx` over `Fin (w κ)`; advice is
`constBits`/`constFin`; coin flips are `uniformBits`.  So the class plausibly contains every
function computed by a probabilistic RAM in `poly(κ)` steps on `poly(κ)` bits with `poly(κ)`
bits of advice, which is `P/poly` and more.

That argument is **not formalised**, and should not be cited as though it were.  What *is*
proved about the class is exactly: the interface clauses (`genPolyTimeModel`,
`genBitOpsEfficient`), (O1), (O2), the PRG sampler, and two membership witnesses
(`polyVal_readBit`, `polyFn_indCpaBitAdversary`).

## Limits to keep in view

* Membership is witnessed by a **derivation**, so there is no decision procedure and no
  extensionality: a function with no derivation is not in the class even if it is morally
  poly-time, and two equal functions may have different derivations.
* Consequently IND-CPA and PRG security against this class remain, formally, *weaker*
  hypotheses than security against all probabilistic polynomial-time adversaries.  The gap is
  now much narrower than before F8 was fixed, but it has not been closed by a theorem.
-/

namespace PRG

/-- A bit vector read as a binary numeral, most significant bit first. -/
def bitsToNat {n : ℕ} (v : BitVector n) : ℕ :=
  v.toList.foldl (fun acc b => 2 * acc + if b then 1 else 0) 0

/-- Index-aware monadic fold: run the step once per `i : Fin n`, threading the state.  The
step *sees* the loop counter, which is what makes width-`κ` inner loops (a ripple-carry adder,
a memory scan) expressible without a data-dependent nesting trick. -/
noncomputable def pmfFold {S : Type} {n : ℕ} (f : Fin n → S → PMF S) (s : S) : PMF S :=
  (List.finRange n).foldl (fun acc i => acc >>= f i) (PMF.pure s)

/-- `n`-fold monadic iteration of a step function.  The state type is *fixed*, which is what
keeps the width from growing: this is the role Hofmann's LFPL diamonds play in a system where
the bound has to be inferred rather than declared. -/
noncomputable def pmfIterate {S : Type} (f : S → PMF S) : ℕ → S → PMF S
  | 0, s => PMF.pure s
  | n + 1, s => pmfIterate f n s >>= f

/-- Value functions generated by the primitives. -/
inductive PolyVal (enc : encryptionScheme) (prg : prgScheme) :
    {D O : ℕ → Type} → famComp D O → Prop
  | protected id {D : ℕ → Type} : PolySized D →
      PolyVal enc prg (D := D) (O := D) (fun _ d => PMF.pure d)
  | fst {D E : ℕ → Type} : PolySized D → PolySized E →
      PolyVal enc prg (D := fun κ => D κ × E κ) (O := D) (fun _ p => PMF.pure p.1)
  | snd {D E : ℕ → Type} : PolySized D → PolySized E →
      PolyVal enc prg (D := fun κ => D κ × E κ) (O := E) (fun _ p => PMF.pure p.2)
  | unit {D : ℕ → Type} : PolySized D →
      PolyVal enc prg (D := D) (O := fun _ => Unit) (fun _ _ => PMF.pure ())
  | pair {D A B : ℕ → Type} (f : (κ : ℕ) → D κ → A κ) (g : (κ : ℕ) → D κ → B κ) :
      PolyVal enc prg (fun κ d => PMF.pure (f κ d)) →
      PolyVal enc prg (fun κ d => PMF.pure (g κ d)) →
      PolyVal enc prg (O := fun κ => A κ × B κ) (fun κ d => PMF.pure (f κ d, g κ d))
  | precomp {D D' O : ℕ → Type} (φ : (κ : ℕ) → D' κ → D κ) (f : famComp D O) :
      PolyVal enc prg (fun κ d => PMF.pure (φ κ d)) → PolyVal enc prg f →
      PolyVal enc prg (fun κ d => f κ (φ κ d))
  | bind {D A B : ℕ → Type} (g : famComp D A) (k : famComp (fun κ => D κ × A κ) B) :
      PolyVal enc prg g → PolyVal enc prg k →
      PolyVal enc prg (fun κ d => g κ d >>= fun a => k κ (d, a))
  | uniformBits {D : ℕ → Type} : PolySized D → ∀ (l : ℕ),
      PolyVal enc prg (D := D) (O := fun _ => Fin l → Bool)
        (fun _ _ => PMF.uniformOfFintype (Fin l → Bool))
  | uniformKeys {D : ℕ → Type} : PolySized D → ∀ (l : ℕ),
      PolyVal enc prg (D := D) (O := fun κ => Fin l → BitVector κ)
        (fun κ _ => PMF.uniformOfFintype (Fin l → BitVector κ))
  -- the bit primitives
  | append (d₁ d₂ : ℕ → ℕ) : PolyLength d₁ → PolyLength d₂ →
      PolyVal enc prg (D := fun κ => BitVector (d₁ κ) × BitVector (d₂ κ))
        (O := fun κ => BitVector (d₁ κ + d₂ κ))
        (fun _ p => PMF.pure (List.Vector.append p.1 p.2))
  | condAppend (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => Bool × BitVector (d κ) × BitVector (d κ))
        (O := fun κ => BitVector (d κ + d κ))
        (fun _ p => PMF.pure (if p.1 then List.Vector.append p.2.2 p.2.1
                                     else List.Vector.append p.2.1 p.2.2))
  | bitExpr (l : ℕ) (b : BitExpr) :
      PolyVal enc prg (D := fun _ => Fin l → Bool) (O := fun _ => Bool)
        (fun _ bv => PMF.pure (evalBitExpr (extendFin false bv) b))
  | bitToVec : PolyVal enc prg (D := fun _ => Bool) (O := fun _ => BitVector 1)
        (fun _ b => PMF.pure (List.Vector.cons b List.Vector.nil))
  | keyVar (l n : ℕ) :
      PolyVal enc prg (D := fun κ => Fin l → BitVector κ) (O := fun κ => BitVector κ)
        (fun _ kv => PMF.pure (extendFin ones kv n))
  | constVec {D : ℕ → Type} : PolySized D → ∀ (d : ℕ → ℕ), PolyLength d →
      PolyVal enc prg (D := D) (O := fun κ => BitVector (d κ)) (fun _ _ => PMF.pure ones)
  | nilVec {D : ℕ → Type} : PolySized D →
      PolyVal enc prg (D := D) (O := fun _ => BitVector 0) (fun _ _ => PMF.pure List.Vector.nil)
  -- the cryptographic primitives: LM18 Definition 1, as generators
  | encrypt (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => BitVector κ × BitVector (d κ))
        (O := fun κ => BitVector ((enc κ).encryptLength (d κ)))
        (fun κ km => (enc κ).encrypt km.1 km.2)
  | prg0 : PolyVal enc prg (D := fun κ => BitVector κ) (O := fun κ => BitVector κ)
        (fun κ seed => PMF.pure ((prg κ).prg0 seed))
  | prg1 : PolyVal enc prg (D := fun κ => BitVector κ) (O := fun κ => BitVector κ)
        (fun κ seed => PMF.pure ((prg κ).prg1 seed))
  -- ## Bit-level computation
  --
  -- The generators above were chosen to make the *reductions* expressible.  Reusing that set
  -- as the *adversary* class was a category error (`CHECKPOINT.md` §3.1, F8): with no way to
  -- get a `Bool` out of a `BitVector`, no distinguisher could depend on its challenge.  These
  -- close that hole.  Read and write take the position **as input**, not fixed per κ, which
  -- is what makes a random-access step expressible in a constant number of generators.
  | index (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => BitVector (d κ) × Fin (d κ)) (O := fun _ => Bool)
        (fun _ p => PMF.pure (p.1.get p.2))
  | update (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => BitVector (d κ) × Fin (d κ) × Bool)
        (O := fun κ => BitVector (d κ))
        (fun _ p => PMF.pure (p.1.set p.2.1 p.2.2))
  | notB : PolyVal enc prg (D := fun _ => Bool) (O := fun _ => Bool)
        (fun _ b => PMF.pure (!b))
  /-- Branch on a bit, at any poly-sized result type.  `condAppend` does this for one specific
      shape; machine simulation needs it in general. -/
  | select {A : ℕ → Type} : PolySized A →
      PolyVal enc prg (D := fun κ => Bool × A κ × A κ) (O := A)
        (fun _ p => PMF.pure (if p.1 then p.2.1 else p.2.2))
  | andB : PolyVal enc prg (D := fun _ => Bool × Bool) (O := fun _ => Bool)
        (fun _ p => PMF.pure (p.1 && p.2))
  | constBool {D : ℕ → Type} : PolySized D → ∀ (b : Bool),
      PolyVal enc prg (D := D) (O := fun _ => Bool) (fun _ _ => PMF.pure b)
  | xorBits (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => BitVector (d κ) × BitVector (d κ))
        (O := fun κ => BitVector (d κ))
        (fun _ p => PMF.pure (List.Vector.map₂ xor p.1 p.2))
  | eqBits (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => BitVector (d κ) × BitVector (d κ)) (O := fun _ => Bool)
        (fun _ p => PMF.pure (decide (p.1 = p.2)))
  /-- An arbitrary bit-vector constant, one per `κ`.  Same non-uniformity justification as
      `constFin`: `d κ` hardwired bits per `κ` is exactly the advice a poly-size circuit family
      is allowed.  `constVec` (all-ones) is the special case the reductions use. -/
  | constBits {D : ℕ → Type} (d : ℕ → ℕ) : PolySized D → PolyLength d →
      ∀ (c : (κ : ℕ) → BitVector (d κ)),
      PolyVal enc prg (D := D) (O := fun κ => BitVector (d κ)) (fun κ _ => PMF.pure (c κ))
  /-- A fixed position, one per `κ`.  Free in a non-uniform model, which is what `queryFn`
      already commits this class to (`CHECKPOINT.md` §3.0, F2): each `κ` gets its own circuit,
      so a per-`κ` wire choice costs nothing.  It carries only `log (d κ)` bits. -/
  | constFin {D : ℕ → Type} (d : ℕ → ℕ) : PolySized D → PolyLength d →
      ∀ (i : (κ : ℕ) → Fin (d κ)),
      PolyVal enc prg (D := D) (O := fun κ => Fin (d κ)) (fun κ _ => PMF.pure (i κ))
  /-- Advance a position by one, cyclically.  Enough to walk a tape. -/
  | finSucc (d : ℕ → ℕ) : PolyLength d →
      PolyVal enc prg (D := fun κ => Fin (d κ)) (O := fun κ => Fin (d κ))
        (fun κ i => PMF.pure (finRotate (d κ) i))
  -- ## Bounded iteration
  --
  -- The declared-bound form.  `p.eval κ` iterations of a step on a **fixed** poly-sized state:
  -- poly-many steps, each poly, and the state cannot widen because its type pins it.  LFPL
  -- needs a payment discipline because it must *infer* the bound from a typing judgement;
  -- generating the class instead lets us simply declare it.
  | iterate (p : Polynomial ℕ) {S : ℕ → Type} : PolySized S → ∀ (step : famComp S S),
      PolyVal enc prg step →
      PolyVal enc prg (D := S) (O := S) (fun κ s => pmfIterate (step κ) (p.eval κ) s)
  /-- The index-aware form.  Needed for anything whose inner loop runs over *positions*, such
      as binary arithmetic on a `κ`-bit register; `iterate` alone cannot express those, because
      its step cannot tell which pass it is on. -/
  | iterateIdx (p : Polynomial ℕ) {S : ℕ → Type} : PolySized S →
      ∀ (step : (κ : ℕ) → (Fin (p.eval κ) × S κ) → PMF (S κ)),
      PolyVal enc prg (D := fun κ => Fin (p.eval κ) × S κ) (O := S) step →
      PolyVal enc prg (D := S) (O := S)
        (fun κ s => pmfFold (fun i t => step κ (i, t)) s)
  /-- Read a register as an address.  Without this a step can only reach positions fixed in
      advance or reached by counting, so random access into a `κ`-wide memory is impossible and
      the class falls well short of poly-time. -/
  | bitsToFin (w d : ℕ → ℕ) : PolyLength w → PolyLength d → ∀ (hpos : ∀ κ, 0 < d κ),
      PolyVal enc prg (D := fun κ => BitVector (w κ)) (O := fun κ => Fin (d κ))
        (fun κ v => PMF.pure ⟨bitsToNat v % d κ, Nat.mod_lt _ (hpos κ)⟩)

/-- Oracle computations generated from `PolyVal` by sequencing and a single query. -/
inductive PolyFn (enc : encryptionScheme) (prg : prgScheme) :
    {I : Type} → {Spec : ℕ → OracleSpec I} → {Domain Output : ℕ → Type} →
    famOracleFn Spec Domain Output → Prop
  | ofPure {I : Type} {Spec : ℕ → OracleSpec I} {D O : ℕ → Type} (f : (κ : ℕ) → D κ → O κ) :
      PolyVal enc prg (fun κ d => PMF.pure (f κ d)) →
      PolyFn enc prg (I := I) (Spec := Spec) (fun κ d => pure (f κ d))
  | ofSample {I : Type} {Spec : ℕ → OracleSpec I} {D O : ℕ → Type} (f : famComp D O) :
      PolyVal enc prg f →
      PolyFn enc prg (I := I) (Spec := Spec) (fun κ d => sample (f κ d))
  | bind {I : Type} {Spec : ℕ → OracleSpec I} {D A B : ℕ → Type}
      (g : famOracleFn Spec D A) (k : famOracleFn Spec (fun κ => D κ × A κ) B) :
      PolyFn enc prg g → PolyFn enc prg k →
      PolyFn enc prg (fun κ d => g κ d >>= fun a => k κ (d, a))
  | precomp {I : Type} {Spec : ℕ → OracleSpec I} {D D' B : ℕ → Type}
      (φ : (κ : ℕ) → D' κ → D κ) (g : famOracleFn Spec D B) :
      PolyVal enc prg (fun κ d => PMF.pure (φ κ d)) → PolyFn enc prg g →
      PolyFn enc prg (fun κ d => g κ (φ κ d))
  | query {I : Type} {Spec : ℕ → OracleSpec I} {D : ℕ → Type} (i : (κ : ℕ) → I)
      (t : (κ : ℕ) → D κ → (Spec κ).domain (i κ)) :
      PolySized (fun κ => (Spec κ).range (i κ)) →
      PolyVal enc prg (fun κ d => PMF.pure (t κ d)) →
      PolyFn enc prg (Output := fun κ => (Spec κ).range (i κ))
        (fun κ d => (OracleComp.lift ((withRandomI Spec κ).query (Sum.inr (i κ)) (t κ d))
          : OracleComp (withRandomI Spec κ) ((Spec κ).range (i κ))))

/-- The generated poly-time predicate: close a function family over the trivial input. -/
def GenPolyTime (enc : encryptionScheme) (prg : prgScheme) : PolyFamOracleCompPred :=
  fun {_ _ _} oa => PolyFn enc prg (fun κ (_ : Unit) => oa κ)

end PRG

namespace PRG

/-- **The bridge.**  `polyTimeFamComp` phrases "this value function is poly-time" as "the
computation that *queries for its input* and then runs it is poly-time".  So every clause of
`PolyTimeModel` stated with `PolyTimeVal` needs `PolyVal f` to imply that form.

Note what it needs: `PolySized` on the **output** as well as the input. -/
theorem polyVal_to_famComp {enc : encryptionScheme} {prg : prgScheme}
    {Input Output : ℕ → Type} (hI : PolySized Input) (hO : PolySized Output)
    (f : famComp Input Output) (hf : PolyVal enc prg f) :
    polyTimeFamComp (GenPolyTime enc prg) f := by
  have hq := PolyFn.query (enc := enc) (prg := prg)
    (Spec := fun κ => simpleCompSpec (Input κ)) (D := fun _ => Unit)
    (fun _ => ()) (fun _ _ => ()) hI (PolyVal.unit PolySized.unit)
  have hs := PolyFn.ofSample (enc := enc) (prg := prg)
    (Spec := fun κ => simpleCompSpec (Input κ))
    (fun κ (p : Unit × Input κ) => f κ p.2)
    (PolyVal.precomp (fun _ (p : Unit × Input _) => p.2) f
      (PolyVal.snd PolySized.unit hI) hf)
  have hp := PolyFn.ofPure (enc := enc) (prg := prg)
    (Spec := fun κ => simpleCompSpec (Input κ))
    (D := fun κ => (Unit × Input κ) × Output κ) (O := Output)
    (fun _ q => q.2)
    (PolyVal.snd (PolySized.unit.prod hI) hO)
  exact PolyFn.bind _ _ hq (PolyFn.bind _ _ hs hp)

end PRG

namespace PRG

/-!
## The interface, discharged

Each clause is the matching constructor.  That is the whole point of generating the class
rather than measuring terms: what used to be fifteen assumptions about an opaque predicate is
now fifteen `rfl`-sized facts about a definition.
-/

/-- **`PolyTimeModel` is a theorem for the generated class.** -/
def genPolyTimeModel (enc : encryptionScheme) (prg : prgScheme) :
    PolyTimeModel (GenPolyTime enc prg) where
  IsPolyTimeFn := PolyFn enc prg
  IsPolyTimeVal := PolyVal enc prg
  valId := PolyVal.id
  valFst := PolyVal.fst
  valSnd := PolyVal.snd
  valUnit := PolyVal.unit
  valPair := PolyVal.pair
  precompVal := PolyVal.precomp
  bindVal := PolyVal.bind
  pureFn := PolyFn.ofPure
  liftVal := PolyFn.ofSample
  bindFn := PolyFn.bind
  precompFn := PolyFn.precomp
  queryFn := PolyFn.query
  closeFn := by
    intro I Spec B g hg
    have h : (fun κ (_ : Unit) => g κ ()) = g := by funext κ u; cases u; rfl
    show PolyFn enc prg (fun κ (_ : Unit) => g κ ())
    rw [h]; exact hg
  uniformBits := PolyVal.uniformBits
  uniformKeys := PolyVal.uniformKeys
  valToFamComp := fun f hD hO hf => polyVal_to_famComp hD hO f hf

/-- **`BitOpsEfficient` is a theorem for the generated class.** -/
def genBitOpsEfficient (enc : encryptionScheme) (prg : prgScheme) :
    BitOpsEfficient (PolyVal enc prg) where
  append := PolyVal.append
  condAppend := PolyVal.condAppend
  bitExpr := PolyVal.bitExpr
  bitToVec := PolyVal.bitToVec
  keyVar := PolyVal.keyVar
  constVec := PolyVal.constVec
  nilVec := PolyVal.nilVec

/-- **LM18 Definition 1 is a generator, not a hypothesis.** -/
theorem genEfficientEncVal (enc : encryptionScheme) (prg : prgScheme) :
    EfficientEncVal (PolyVal enc prg) enc := fun d hd => PolyVal.encrypt d hd

theorem genEfficientPrgVal (enc : encryptionScheme) (prg : prgScheme) :
    EfficientPrgVal (PolyVal enc prg) prg := ⟨PolyVal.prg0, PolyVal.prg1⟩

/-- **(O1) at a concrete predicate.** -/
theorem gen_encReduction_polyTime (enc : encryptionScheme) (prg : prgScheme)
    (Hlen : LengthPoly enc) :
    EncReductionPolyTime (GenPolyTime enc prg) enc prg :=
  encReduction_polyTime (genPolyTimeModel enc prg) (genBitOpsEfficient enc prg) enc prg
    (genEfficientEncVal enc prg) (genEfficientPrgVal enc prg) Hlen

/-- **(O2) at a concrete predicate.** -/
theorem gen_efficientEvalPrg (enc : encryptionScheme) (prg : prgScheme)
    (Hlen : LengthPoly enc) :
    EfficientEvalPrg (GenPolyTime enc prg) enc prg :=
  efficientEvalPrg_holds (genPolyTimeModel enc prg) (genBitOpsEfficient enc prg) enc prg Hlen
    (genEfficientEncVal enc prg) (genEfficientPrgVal enc prg)

/-- **The PRG sampler at a concrete predicate.** -/
theorem gen_prgEnvSampler_polyTime (enc : encryptionScheme) (prg : prgScheme)
    {s : Shape} (expr : Expression s) (targetSeed : Expression Shape.KeyS) (idx0 idx1 : ℕ) :
    GenPolyTime enc prg (prgEnvSampler expr targetSeed idx0 idx1) :=
  prgEnvSampler_polyTime (genPolyTimeModel enc prg) expr targetSeed idx0 idx1

/-!
## Sanity check: the class now contains an adversary that looks at its challenge

Finding F8 was that no generator took a `BitVector` to a `Bool`, so no distinguisher could
depend on its input at all.  These two are the positive replacement for that check — and
unlike a formalised *negative* statement, they stay true as the class grows.
-/

/-- Reading a fixed bit of a bit vector is in the class. -/
theorem polyVal_readBit (enc : encryptionScheme) (prg : prgScheme)
    (d : ℕ → ℕ) (hd : PolyLength d) (i : (κ : ℕ) → Fin (d κ)) :
    PolyVal enc prg (D := fun κ => BitVector (d κ)) (O := fun _ => Bool)
      (fun κ v => PMF.pure (v.get (i κ))) :=
  PolyVal.precomp (fun κ (v : BitVector (d κ)) => (v, i κ))
    (fun _ p => PMF.pure (p.1.get p.2))
    (PolyVal.pair _ _ (PolyVal.id (PolySized.bitVector d hd))
      (PolyVal.constFin d (PolySized.bitVector d hd) hd i))
    (PolyVal.index d hd)

/-- The length of a ciphertext for a *fixed* message length is polynomially bounded. -/
theorem encryptLength_polyLength {enc : encryptionScheme} (Hlen : LengthPoly enc) (n : ℕ) :
    PolyLength (fun κ => (enc κ).encryptLength n) := by
  obtain ⟨p, hp⟩ := Hlen
  exact ⟨p.comp (Polynomial.C n + Polynomial.X), fun κ => by simpa using hp κ n⟩

/-- **And so is a real IND-CPA distinguisher**: pick two messages, query the left-or-right
oracle, report a bit of the ciphertext.  This is exactly the shape F8 said was unreachable —
the `Bool` it outputs depends on the oracle's answer. -/
theorem polyFn_indCpaBitAdversary (enc : encryptionScheme) (prg : prgScheme)
    (Hlen : LengthPoly enc) (n : ℕ) (m : (κ : ℕ) → BitVector n × BitVector n)
    (i : (κ : ℕ) → Fin ((enc κ).encryptLength n)) :
    PolyFn enc prg (Spec := fun κ => oracleSpecIndCpa κ (enc κ)) (Domain := fun _ => Unit)
      (Output := fun _ => Bool)
      (fun κ _ =>
        (OracleComp.lift ((withRandomI (fun κ => oracleSpecIndCpa κ (enc κ)) κ).query
            (Sum.inr n) (m κ))
          : OracleComp (withRandomI (fun κ => oracleSpecIndCpa κ (enc κ)) κ)
              (BitVector ((enc κ).encryptLength n))) >>= fun c => pure (c.get (i κ))) := by
  have hp : PolyLength (fun κ => (enc κ).encryptLength n) := encryptLength_polyLength Hlen n
  have hsz : PolySized (fun κ => BitVector ((enc κ).encryptLength n)) :=
    PolySized.bitVector _ hp
  have hm : PolyVal enc prg (D := fun _ => Unit)
      (O := fun _ => BitVector n × BitVector n) (fun κ _ => PMF.pure (m κ)) :=
    PolyVal.pair (fun κ _ => (m κ).1) (fun κ _ => (m κ).2)
      (PolyVal.constBits (fun _ => n) PolySized.unit (PolyLength.const n) (fun κ => (m κ).1))
      (PolyVal.constBits (fun _ => n) PolySized.unit (PolyLength.const n) (fun κ => (m κ).2))
  have hq := PolyFn.query (enc := enc) (prg := prg)
    (Spec := fun κ => oracleSpecIndCpa κ (enc κ)) (D := fun _ => Unit)
    (fun _ => n) (fun κ (_ : Unit) => m κ) hsz hm
  have hk := PolyFn.ofPure (enc := enc) (prg := prg)
    (Spec := fun κ => oracleSpecIndCpa κ (enc κ))
    (fun κ (q : Unit × BitVector ((enc κ).encryptLength n)) => q.2.get (i κ))
    (PolyVal.precomp
      (fun κ (q : Unit × BitVector ((enc κ).encryptLength n)) => q.2)
      (fun κ v => PMF.pure (v.get (i κ)))
      (PolyVal.snd PolySized.unit hsz) (polyVal_readBit enc prg _ hp i))
  exact PolyFn.bind _ _ hq hk

end PRG
